# Below method is used to select approapriate feature for model prediction in Random forest

To identify relevant feature we are using Boruta method

Description about Boruta Py

BorutaPy is a Python implementation of the Boruta feature selection method, and it's a valuable tool in machine learning for several reasons. Here's a breakdown of its uses:  

Core Purpose: Feature Selection

    Identifying Relevant Features:
        The primary goal of BorutaPy is to determine which features in a dataset are genuinely important for predicting the target variable.   

It goes beyond simply ranking features; it aims to find "all relevant" features, meaning it tries to capture all the features that carry useful information.  

Reducing Noise and Redundancy:

    Datasets often contain many features, some of which may be irrelevant or redundant. BorutaPy helps to eliminate these, leading to cleaner and more efficient models.   

Improving Model Performance:

    By focusing on the most relevant features, BorutaPy can improve the accuracy and generalization ability of machine learning models.   

        It can also prevent overfitting, which occurs when a model learns the noise in the data rather than the underlying patterns.
    Enhancing Interpretability:
        A model with fewer, more relevant features is easier to understand and interpret. This is particularly important in domains where explainability is crucial.

How BorutaPy Works (in simplified terms):

    It creates "shadow features" by making shuffled copies of the original features.   

It trains a machine learning model (often a Random Forest) on the extended dataset, which includes both the original and shadow features.  
It compares the importance of the original features to the importance of the shadow features.  
Features that consistently outperform the shadow features are deemed important.  

Key Benefits:

    "All-relevant" Feature Selection:
        Unlike some other methods that aim for a minimal set of features, BorutaPy tries to find all features that are relevant to the outcome.   

Robustness:

    The use of shadow features and statistical tests makes BorutaPy a robust method for feature selection.

Compatibility:

    BorutaPy is compatible with various ensemble machine learning models from scikit-learn.
    
 BorutaPy is a powerful tool for data scientists and machine learning practitioners who want to identify the most important features in their datasets. It helps to build more accurate, efficient, and interpretable models.

In [ ]:
pip install Boruta

In [1]:
#import required libraries

import pandas as pd
import numpy  as np

from sklearn.ensemble import  RandomForestClassifier
from boruta import BorutaPy
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

In [2]:
#import data from github

URL ="https://raw.githubusercontent.com/Aditya1001001/English-Premier-League/master/pos_modelling_data.csv"

df = pd.read_csv(URL)

In [6]:

#read first 5 records
df.head()

,Position,Clean sheets,Goals conceded,Tackles,Tackle success %,Blocked shots,Interceptions,Clearances,Recoveries,Successful 50/50s,...,Shots,Shooting accuracy %,Saves,Penalties saved,age,value_eur,overall,Arial Saves,Duels %,Aerial battles %
0,Midfielder,0.0,0.0,4.0,100,0.0,1.0,0.0,9.0,4.0,...,2.0,50,0.0,0.0,21,4400000,72,0.0,46.153846,25.000000
1,Defender,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0.0,0.0,22,10500000,77,0.0,0.000000,0.000000
2,Forward,0.0,0.0,10.0,0,11.0,1.0,19.0,0.0,0.0,...,42.0,36,0.0,0.0,19,7500000,73,0.0,0.000000,0.000000
3,Midfielder,0.0,0.0,9.0,56,3.0,9.0,14.0,40.0,12.0,...,10.0,30,0.0,0.0,31,4800000,74,0.0,55.384615,58.333333
4,Midfielder,0.0,0.0,22.0,59,5.0,14.0,0.0,58.0,6.0,...,11.0,18,0.0,0.0,28,0,83,0.0,40.869565,36.666667

In [7]:

#get dataframe structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1793 entries, 0 to 1792
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Position             1793 non-null   object
 1   Clean sheets         1793 non-null   float64
 2   Goals conceded       1793 non-null   float64
 3   Tackles              1793 non-null   float64
 4   Tackle success %     1793 non-null   int64
 5   Blocked shots        1793 non-null   float64
 6   Interceptions        1793 non-null   float64
 7   Clearances           1793 non-null   float64
 8   Recoveries           1793 non-null   float64
 9   Successful 50/50s    1793 non-null   float64
 10  Own goals            1793 non-null   float64
 11  Assists              1793 non-null   int64
 12  Passes               1793 non-null   int64
 13  Passes per match     1793 non-null   float64
 14  Big chances created  1793 non-null   float64
 15  Crosses              1793 non-null   float64
 16  Cross accuracy %     1793 non-null   int64
 17  Through balls        1793 non-null   float64
 18  Accurate long balls  1793 non-null   float64
 19  Yellow cards         1793 non-null   int64
 20  Red cards            1793 non-null   int64
 21  Fouls                1793 non-null   int64
 22  Offsides             1793 non-null   float64
 23  Goals                1793 non-null   int64
 24  Goals per match      1793 non-null   float64
 25  Shots                1793 non-null   float64
 26  Shooting accuracy %  1793 non-null   int64
 27  Saves                1793 non-null   float64
 28  Penalties saved      1793 non-null   float64
 29  age                  1793 non-null   int64
 30  value_eur            1793 non-null   int64
 31  overall              1793 non-null   int64
 32  Arial Saves          1793 non-null   float64
 33  Duels %              1793 non-null   float64
 34  Aerial battles %     1793 non-null   float64
dtypes: float64(22), int64(12), object(1)
memory usage: 490.4+ KB

In [5]:
# as position variable is output drop it from dataset and create Independent / input  X variable dataset

x = df.drop('Position',axis= 1)

In [9]:
#create dependent / output variable dataset that we are predicting

y= df['Position']

In [10]:
#split data in train, test dataset
x_train,x_test, y_train, y_test  = train_test_split(x,y, test_size=0.2, random_state= 1)

In [13]:
#fit random forest classifier
rf_all_features =RandomForestClassifier(random_state= 1 ,n_estimators =1000 ,max_depth =5)

In [14]:
rf_all_features

RandomForestClassifier(max_depth=5, n_estimators=1000, random_state=1)

In [15]:
#try to fit the model and check the accuracy scope
rf_all_features.fit(x_train , y_train)

accuracy_score(y_test, rf_all_features.predict(x_test))

0.7298050139275766

In [16]:
#check indepedent train array

np.array(x_train)

array([[ 0.        ,  0.        , 21.        , ...,  0.        ,
        55.88235294, 61.11111111],
       [ 0.        ,  0.        , 16.        , ...,  0.        ,
        35.6097561 , 20.54794521],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 6.        , 39.        , 33.        , ...,  0.        ,
        62.98342541, 61.46788991],
       [ 0.        ,  0.        , 41.        , ...,  0.        ,
        45.36585366, 41.17647059]])

In [18]:
#apply baruta for random forest model

rfc =RandomForestClassifier(random_state= 1 ,n_estimators =1000 ,max_depth =5)

boruta_selector =BorutaPy(rfc, n_estimators='auto', verbose=2, random_state= 1)

boruta_selector.fit(np.array(x_train), np.array(y_train))

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	34
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	34
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	34
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	34
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	34
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	34
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	34
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	29
Tentative: 	5
Rejected: 	0
Iteration: 	9 / 100
Confirmed: 	29
Tentative: 	3
Rejected: 	2
Iteration: 	10 / 100
Confirmed: 	29
Tentative: 	3
Rejected: 	2
Iteration: 	11 / 100
Confirmed: 	29
Tentative: 	3
Rejected: 	2
Iteration: 	12 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	13 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	14 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	15 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	16 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	17 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	18 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	19 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	20 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	21 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	22 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	23 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	24 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	25 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	26 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	27 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	28 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	29 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	30 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	31 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	32 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	33 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	34 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	35 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	36 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	37 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	38 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	39 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	40 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	41 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	42 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	43 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	44 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	45 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	46 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	47 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	48 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	49 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	50 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	51 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	52 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	53 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	54 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	55 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	56 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	57 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	58 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	59 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	60 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	61 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	62 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	63 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	64 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	65 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	66 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	67 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	68 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	69 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	70 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	71 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	72 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	73 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	74 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	75 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	76 / 100
Confirmed: 	30
Tentative: 	2
Rejected: 	2
Iteration: 	77 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	78 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	79 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	80 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	81 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	82 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	83 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	84 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	85 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	86 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	87 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	88 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	89 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	90 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	91 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	92 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	93 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	94 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	95 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	96 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	97 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	98 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2
Iteration: 	99 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2


BorutaPy finished running.

Iteration: 	100 / 100
Confirmed: 	31
Tentative: 	1
Rejected: 	2

BorutaPy(estimator=RandomForestClassifier(max_depth=5, n_estimators=160,
                                          random_state=RandomState(MT19937) at 0x21ED1555E40),
         n_estimators='auto',
         random_state=RandomState(MT19937) at 0x21ED1555E40, verbose=2)

In [19]:
#print ranking generated by boruta selector

print('ranking:' , boruta_selector.ranking_)
print("no. of signifant features " , boruta_selector.n_features_)

ranking: [1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 4 1 1 1 1 1 1 1 2 1 1 1 1 1 1]
no. of signifant features  31

In [23]:
#get the list of columns available in training set

list(x_train.columns)

['Clean sheets',
 'Goals conceded',
 'Tackles',
 'Tackle success %',
 'Blocked shots',
 'Interceptions',
 'Clearances',
 'Recoveries',
 'Successful 50/50s',
 'Own goals',
 'Assists',
 'Passes',
 'Passes per match',
 'Big chances created',
 'Crosses',
 'Cross accuracy %',
 'Through balls',
 'Accurate long balls',
 'Yellow cards',
 'Red cards',
 'Fouls',
 'Offsides',
 'Goals',
 'Goals per match',
 'Shots',
 'Shooting accuracy %',
 'Saves',
 'Penalties saved',
 'age',
 'value_eur',
 'overall',
 'Arial Saves',
 'Duels %',
 'Aerial battles %']

In [24]:
#create dataframe of feature names and ranking and sort it with raking

select_rf_features =pd.DataFrame({'features':list(x_train.columns) ,'ranking':boruta_selector.ranking_ })
select_rf_features.sort_values(by= 'ranking')

               features  ranking
0          Clean sheets        1
31          Arial Saves        1
30              overall        1
29            value_eur        1
28                  age        1
26                Saves        1
25  Shooting accuracy %        1
24                Shots        1
23      Goals per match        1
22                Goals        1
21             Offsides        1
20                Fouls        1
18         Yellow cards        1
17  Accurate long balls        1
32              Duels %        1
16        Through balls        1
14              Crosses        1
1        Goals conceded        1
2               Tackles        1
3      Tackle success %        1
4         Blocked shots        1
5         Interceptions        1
6            Clearances        1
15     Cross accuracy %        1
7            Recoveries        1
10              Assists        1
11               Passes        1
12     Passes per match        1
13  Big chances created        1
8     Successful 50/50s        1
33     Aerial battles %        1
27      Penalties saved        2
9             Own goals        3
19            Red cards        4

In [38]:
#remove below features from train set and its rank is more than 1 
#Penalties saved , Own goals,Red cards

x_filter_train = x_train.drop(['Penalties saved','Own goals','Red cards'], axis= 1)

x_filter_test = x_test.drop (['Penalties saved','Own goals','Red cards'], axis= 1)

x_filter_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1434 entries, 1307 to 1061
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Clean sheets         1434 non-null   float64
 1   Goals conceded       1434 non-null   float64
 2   Tackles              1434 non-null   float64
 3   Tackle success %     1434 non-null   int64
 4   Blocked shots        1434 non-null   float64
 5   Interceptions        1434 non-null   float64
 6   Clearances           1434 non-null   float64
 7   Recoveries           1434 non-null   float64
 8   Successful 50/50s    1434 non-null   float64
 9   Assists              1434 non-null   int64
 10  Passes               1434 non-null   int64
 11  Passes per match     1434 non-null   float64
 12  Big chances created  1434 non-null   float64
 13  Crosses              1434 non-null   float64
 14  Cross accuracy %     1434 non-null   int64
 15  Through balls        1434 non-null   float64
 16  Accurate long balls  1434 non-null   float64
 17  Yellow cards         1434 non-null   int64
 18  Fouls                1434 non-null   int64
 19  Offsides             1434 non-null   float64
 20  Goals                1434 non-null   int64
 21  Goals per match      1434 non-null   float64
 22  Shots                1434 non-null   float64
 23  Shooting accuracy %  1434 non-null   int64
 24  Saves                1434 non-null   float64
 25  age                  1434 non-null   int64
 26  value_eur            1434 non-null   int64
 27  overall              1434 non-null   int64
 28  Arial Saves          1434 non-null   float64
 29  Duels %              1434 non-null   float64
 30  Aerial battles %     1434 non-null   float64
dtypes: float64(20), int64(11)
memory usage: 358.5 KB

In [40]:
x_filter_train.shape

(1434, 31)

In [41]:
x_filter_test.shape

(359, 31)

In [45]:

#run boruta method to indetify relevant feature

boruta_selector.fit(np.array(x_filter_train), np.array(y_train))

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	31
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	31
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	31
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	31
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	31
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	31
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	31
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	29
Tentative: 	2
Rejected: 	0
Iteration: 	9 / 100
Confirmed: 	29
Tentative: 	2
Rejected: 	0
Iteration: 	10 / 100
Confirmed: 	29
Tentative: 	2
Rejected: 	0
Iteration: 	11 / 100
Confirmed: 	29
Tentative: 	2
Rejected: 	0
Iteration: 	12 / 100
Confirmed: 	31
Tentative: 	0
Rejected: 	0


BorutaPy finished running.

Iteration: 	13 / 100
Confirmed: 	31
Tentative: 	0
Rejected: 	0

BorutaPy(estimator=RandomForestClassifier(max_depth=5, n_estimators=157,
                                          random_state=RandomState(MT19937) at 0x21ED1555E40),
         n_estimators='auto',
         random_state=RandomState(MT19937) at 0x21ED1555E40, verbose=2)

In [46]:



#select important feature



#x_imp_train =boruta_selector.transform(np.array(x_train))

x_imp_train = boruta_selector.transform(np.array(x_filter_train))

In [47]:
#x_filter_test
#x_imp_test= boruta_selector.transform(np.array(x_test))

x_imp_test= boruta_selector.transform(np.array(x_filter_test))

In [48]:
rf_boruta =RandomForestClassifier(random_state=1, n_estimators= 1000, max_depth=5)

In [49]:
rf_boruta.fit(x_imp_train, y_train)

RandomForestClassifier(max_depth=5, n_estimators=1000, random_state=1)

In [50]:
#checking revised accuracy after removing irrelevant features

accuracy_score(y_test, rf_boruta.predict(x_imp_test))

0.7325905292479109