# ICA
ML ICA stands for Machine Learning Independent Component Analysis. It's a combination of Independent Component Analysis (ICA) with machine learning techniques, aiming to improve and extend the capabilities of traditional ICA. Here's a breakdown:

Understanding the Core Concepts:

    Independent Component Analysis (ICA):
        ICA is a statistical technique used to separate a multivariate signal into additive subcomponents.
        It assumes that the observed signals are linear mixtures of statistically independent source signals.
        The goal is to recover these independent source signals from the mixed observations.
        A classic example is the "cocktail party problem," where ICA attempts to separate individual voices from a recording of multiple people speaking simultaneously.

    Machine Learning (ML):
        ML involves algorithms that learn patterns from data without explicit programming.
        It encompasses various techniques like supervised learning, unsupervised learning, and reinforcement learning.
        ML can be used for tasks such as classification, regression, clustering, and dimensionality reduction.

How ML Enhances ICA:

ML techniques can improve ICA in several ways:

    Handling Nonlinear Mixtures:
        Traditional ICA assumes linear mixtures. ML methods, such as neural networks, can handle more complex nonlinear relationships between source signals and observed signals.
        This is crucial for real-world scenarios where the mixing process is often nonlinear.
    Improving Robustness:
        ML algorithms can be trained to be more robust to noise and outliers in the data, which can affect the performance of traditional ICA.
    Automating Parameter Selection:
        ICA algorithms often require careful selection of parameters. ML can be used to automate this process, optimizing the parameters for specific datasets.
    Dealing with Underdetermined ICA:
        In underdetermined ICA, the number of source signals is greater than the number of observed signals. ML techniques, such as sparse coding and deep learning, can help to address this challenge.
    Feature Extraction:
        The Independent components that ICA finds can be used as features for machine learning algorithms. This can improve the performance of downstream machine learning tasks.
    Improving speed and efficency:
        Machine learning can be used to create faster approximations of ICA algorithms.

In [2]:
import pandas as pd
import numpy  as np
from sklearn.decomposition import FastICA
import matplotlib.pyplot as plt

from sklearn.datasets import load_wine

In [5]:
df = pd.DataFrame(load_wine() ['data'] ,columns= load_wine()['feature_names'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

In [7]:
df.head()

   alcohol  malic_acid   ash  alcalinity_of_ash  ...  color_intensity   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43               15.6  ...             5.64  1.04                          3.92   1065.0
1    13.20        1.78  2.14               11.2  ...             4.38  1.05                          3.40   1050.0
2    13.16        2.36  2.67               18.6  ...             5.68  1.03                          3.17   1185.0
3    14.37        1.95  2.50               16.8  ...             7.80  0.86                          3.45   1480.0
4    13.24        2.59  2.87               21.0  ...             4.32  1.04                          2.93    735.0

[5 rows x 13 columns]

In [8]:
df['y'] =pd.DataFrame(load_wine() ['target'])

In [9]:
df.head()

   alcohol  malic_acid   ash  alcalinity_of_ash  ...   hue  od280/od315_of_diluted_wines  proline  y
0    14.23        1.71  2.43               15.6  ...  1.04                          3.92   1065.0  0
1    13.20        1.78  2.14               11.2  ...  1.05                          3.40   1050.0  0
2    13.16        2.36  2.67               18.6  ...  1.03                          3.17   1185.0  0
3    14.37        1.95  2.50               16.8  ...  0.86                          3.45   1480.0  0
4    13.24        2.59  2.87               21.0  ...  1.04                          2.93    735.0  0

[5 rows x 14 columns]

In [12]:

#create ICA of 3 components
ICA = FastICA(n_components=3)

IndependentComp_values =ICA.fit_transform(df.values)

In [13]:
print('#Final indepedent components#')

reducedata =pd.DataFrame(data=IndependentComp_values, columns=['IC1','IC2','IC3'])

print(reducedata.head())

#Final indepedent components#
        IC1       IC2       IC3
0  1.586704  1.502620 -0.043760
1  0.412461  1.222724 -2.082601
2 -0.958375  1.175032  0.123987
3 -0.758489  2.195594  0.384005
4  1.139884  0.241742  0.809154